server.port: 8090 # is for local dev necessary

spring:
  datasource:
    url: jdbc:postgresql://${CAMUNDA_DB_HOST}:${CAMUNDA_DB_PORT:5432}/${CAMUNDA_DB_NAME}
    username: ${CAMUNDA_DB_USER}
    password: ${CAMUNDA_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

camunda.bpm:
  admin-user:
    id: ${CAMUNDA_ADMIN_USERNAME}
    password: ${CAMUNDA_ADMIN_PASSWORD}
    firstName: ${CAMUNDA_ADMIN_FIRSTNAME}
    lastName: ${CAMUNDA_ADMIN_LASTNAME}
  filter:
    create: All Tasks
  job-execution:
    max-wait: 10000

logging:
  level:
    pro.taskana: INFO
